name: Bump

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Specify a rc/beta/other version suffix'
        required: false

jobs:
  version_check_and_tag:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.BUMPER_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Run Python Script
      run: |
        last_version=$(git describe --tags --abbrev=0)
        python .github/workflows/bump.py "$last_version"
    - name: Set new version
      run: |
        new_version=${{ env.new_version }}
        echo "new_version is $new_version"

        if [ -n "$new_version" ]; then
          git tag "v$new_version$SUFFIX"
          git push --tags
        else
          echo "No new version detected."
        fi

      env:
        SUFFIX: ${{ github.event.inputs.suffix }}
