name: Check python compatibility

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testpyversion:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: pytest
        shell: bash
        run: |
          set -e
          python --version
          pip install peroxymanova --find-links dist --force-reinstall --verbose --no-index --no-deps
          pip install peroxymanova
          pip install -r pytests/requirements.txt
          pip install pytest
          pytest
